from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views
from .views import save_template,get_template,get_client_header_footer
from .views import convert_pdf_to_word # by rohan jangid 14-04-2025
from .views import update_non_reportable_status,get_dicom_notes


# from django.contrib.auth import views

urlpatterns = [
    path('', views.login, name='login'),
    path('data', views.server_data, name='fetch_PACS'),
    path('logout/', views.logout, name='logout'),
    path('regrdo/', views.regrdo, name='regrdo'),
    path('reginst', views.reginst, name='reginst'),
    path('reginst/personal', views.InstPersonalInfo, name='reginst.personal'),
    path('reginst/modalities', views.InstitutionModalities, name='reginst.modalities'),
    path('regrdo/personal', views.PersonalInfo, name='regrdo.personal'),
    path('regrdo/qualificationdetails', views.QualificationDetails, name='regrdo.qualificationdetails'),
    path('regrdo/workexp', views.WorkExp, name='regrdo.workexp'),
    path('regrdo/bankinginfo', views.BankingInfo, name='regrdo.bankinginfo'),
    path('regrdo/reportingarea', views.ReportingArea, name='regrdo.reportingarea'),
    path('regrdo/timeavailability', views.TimeAvailability, name='regrdo.timeavailability'),
    path('prordo', views.prordo, name='prordo'),
    path('proinst', views.proinst, name='proinst'),
    path('user-exists', views.userExists, name='userexists'),
    path('number-exists', views.numberExists, name='numberexists'),
    path('phone-exists', views.phoneExists, name='phoneexists'),
    path('patientdata', views.patientData, name='patientdata'),
    path('patientdetails', views.patientDetails, name='patientdetails'),
    path('audiopatientdata', views.audiopatientDetails, name='audiopatientdata'),
    path('optometrydata', views.optopatientDetails, name='optometrydata'),
    path('vitalpatientdata', views.vitalpatientDetails, name='vitalpatientdata'),
    path('uploadcsv', views.uploadcsv, name='uploadcsv'),
    path('uploadcsvforaudio', views.uploadcsvforaudio, name='uploadcsvforaudio'),
    path('uploadcsvforopto', views.uploadcsvforopto, name='uploadcsvforopto'),
    path('uploadcsvforvital', views.uploadcsvforvital, name='uploadcsvforvital'),
    path('serviceslist', views.PersonalInfo, name='serviceslist'),
    path('ecgallocation', views.ecgallocation, name='ecgallocation'),
    path('xrayallocation', views.xrayallocation, name='xrayallocation'),
    path('xrayallocationreverse', views.xrayallocationreverse, name='xrayallocationreverse'),
    path('audiometry', views.audiometry, name='audiometry'),
    path('allocation', views.allocation, name='ecgcoordinator'),
    #by rohan jangid
    path('assign-cardiologist/', views.assign_cardiologist, name='assign_cardiologist'),
    path('update_urgent_status/<int:patient_id>/', views.update_urgent_status, name='update_urgent_status'),
    path('update-non-reportable/<int:patient_id>/', update_non_reportable_status, name='update-non-reportable'),
    #upto this by rohan jangid
    path('allocation1', views.allocation1, name='xraycoordinator'),
    path('assign-radiologist/', views.assign_radiologist, name='assign_radiologist'),
    path('assign-radiologist1/', views.assign_radiologist1, name='assign_radiologist1'),
    path('assign-radiologist2/', views.assign_radiologist2, name='assign_radiologist2'),
    path('allocationcoordinator1', views.allocationcoordinator1, name='corporatecoordinator'),
    path('allocate/', views.allocate, name='allocate'),
    path('allocate1/', views.allocate1, name='allocate1'),
    path('allocatecoordinator1/', views.allocatecoordinator1, name='allocatecoordinator1'),
    path('coordinatorallocate1/', views.coordinatorallocate1, name='coordinatorallocate1'),
    path('fetch_patient_data', views.fetch_patient_data, name='fetch_patient_data'),
    #path('pacsuploader/', views.pacsuploader, name='pacsuploader'),
    #path('upload/', views.upload_dicom, name='upload_dicom'),
    path('api/update_patient_done_status/<str:patient_id>/', views.update_patient_done_status, name='update_patient_done_status'),
    path('api/update_patient_done_status_xray/<str:study_id>/', views.update_patient_done_status_xray, name='update_patient_done_status_xray'),
    path('update_urgent_status_xray/<str:patient_id>/', views.update_urgent_status_xray, name='update_urgent_status_xray'),
    path('update_mlc_status_xray/<str:patient_id>/', views.update_mlc_status_xray, name='update_mlc_status_xray'),
    path('update_isDone_status_xray/<str:patient_id>/', views.update_isDone_status_xray, name='update_isDone_status_xray'),
    path('update_vip_status_xray/<str:patient_id>/', views.update_vip_status_xray, name='update_vip_status_xray'),
    path('api/reject_patient_status/<str:patient_id>/', views.reject_patient_status, name='reject_patient_status'),
    path('upload_ecg_pdf/', views.upload_ecg_pdf, name='upload_ecg_pdf'),
    path('upload_xray_pdf/', views.upload_xray_pdf, name='upload_xray_pdf'),
    path('upload_vitals_pdf/', views.upload_vitals_pdf, name='upload_vitals_pdf'),
    path('upload_optometry_pdf/', views.upload_optometry_pdf, name='upload_optometry_pdf'),
    path('upload_audiometry_pdf/', views.upload_audiometry_pdf, name='upload_audiometry_pdf'),
    path('get-csrf-token/', views.get_csrf_token, name='get_csrf_token'),
    path('xray_pdf_report/', views.xray_pdf_report, name='xray_pdf_report'),
    path('client_dashboard/', views.client_dashboard, name='client_dashboard'),
    path('convert_pdf_to_word/<int:report_id>/', convert_pdf_to_word, name='convert_pdf_to_word'),#by rohan jangid 14-04-2025
    path('ecg_pdf_report/', views.ecg_pdf_report, name='ecg_pdf_report'),
    path('vitals_pdf_report/', views.vitals_pdf_report, name='vitals_pdf_report'),
    path('optometry_pdf_report/', views.optometry_pdf_report, name='optometry_pdf_report'),
    path('audiometry_pdf_report/', views.audiometry_pdf_report, name='audiometry_pdf_report'),
    path('get_excel/', views.get_excel, name='get_excel'),
    path('clientdata/client/', views.client_dashboard, name='client'),
    path('xray-report/<int:pdf_id>/add-logo-with-pdf/', views.add_logo_to_pdf, name='add_logo_to_pdf'),
    path('download-with-logo/<int:pdf_id>/', views.download_pdf_with_logo, name='download_pdf_with_logo'),
    path('ecg-report/<int:pdf_id>/download-ecg-with-logo/', views.add_logo_to_ecg_pdf, name='download_ecg_pdf_with_logo'),
    path('update_history/', views.update_clinical_history, name='clinical_history'),
    path('optometrylist', views.optometrylist, name='optometrylist'),
    path('vitalslist', views.vitalslist, name='vitalslist'),
    path('api/patient-ids/', views.patient_id_list, name='api_patient_ids'),
    path('delete_all_patients', views.delete_all_patients, name='delete_all_patients'),
    path('delete_all_patients_opto', views.delete_all_patients_opto, name='delete_all_patients_opto'),
    path('add_patient', views.add_patient, name='add_patient'),
    path('add_patient_opto', views.add_patient_opto, name='add_patient_opto'),
    path('add_patient_audio', views.add_patient_audio, name='add_patient_audio'),
    path('delete_all_patients_audio', views.delete_all_patients_audio, name='delete_all_patients_audio'),
    path('reporting_status', views.ReportingStatus, name='reporting_status'),
    path('set_target', views.SetTarget, name='set_target'),
    path('ecg_reporting_status', views.ECGReportingStatus, name='ecg_reporting_status'),
    path('ecg_set_target', views.ECGSetTarget, name='ecg_set_target'),
    path('vaccinationlist', views.vaccinationlist, name='vaccinationlist'),
    path('delete_all_patients_for_vaccination', views.delete_all_patients_for_vaccination, name='delete_all_patients_for_vaccination'),
    path('add_patient_for_vaccination', views.add_patient_for_vaccination, name='add_patient_for_vaccination'),
    path('uploadcsvforvaccination', views.uploadcsvforvaccination, name='uploadcsvforvaccination'),
    path('VaccinationPatientData', views.vaccinationpatientDetails, name='VaccinationPatientData'),
    # Adding all the paths and routes for the ecg and xray automation. - Himanshu.
    path('ecglist', views.ecglist, name='ecglist'),
    path('xraylist', views.xraylist, name='xraylist'),
    path('delete_all_patients_for_ecg', views.delete_all_patients_for_ecg, name='delete_all_patients_for_ecg'),
    path('delete_all_patients_for_xray', views.delete_all_patients_for_xray, name='delete_all_patients_for_xray'),
    path('add_patient_for_ecg', views.add_patient_for_ecg, name='add_patient_for_ecg'),
    path('add_patient_for_xray', views.add_patient_for_xray, name='add_patient_for_xray'),
    path('uploadcsvforecg', views.uploadcsvforecg, name='uploadcsvforecg'),
    path('uploadcsvforxray', views.uploadcsvforxray, name='uploadcsvforxray'),
    path('ecgPatientData', views.ecgpatientDetails, name='ecgPatientData'),
    path('xrayPatientData', views.xraypatientDetails, name='xrayPatientData'),
    # End of ecg and xray routes. - Himanshu.
    path('upload/', views.upload_files, name='upload_files'),
    # path('auto_sync/', views.Auto_Sync, name='get_dcm_files'),
    path('upload-ecg/', views.upload_ecg, name='upload_ecg'),
    path('clientdata/', views.clientdata, name='clientdata'),
    path('edit-dicom-data/<int:pk>/', views.edit_dicom_data, name='edit_dicom_data'),
    path('edit-dicom-data-coordinator/<int:pk>/', views.edit_dicom_data_coordinator, name='edit_dicom_data_coordinator'),
    path('edit-ecg-data-coordinator/<int:pk>/', views.edit_ecg_data_coordinator, name='edit_ecg_data_coordinator'),
    path('supercoordinator/', views.supercoordinator_view, name='supercoordinator'),
    path('supercoordinator/edit/<int:client_id>/', views.supercoordinator_view, name='edit_client'),
    path('send_whatsapp/', views.send_whatsapp, name='send_whatsapp'),
    path('update_twostepcheck/<str:patient_id>/', views.update_twostepcheck, name='update_twostepcheck'),
    path('update_NonReportable/<str:patient_id>/', views.update_NonReportable, name='update_NonReportable'),
    path('review_page', views.review_page, name='review_page'),
    path('corporate-doctor-dashboard/', views.corporate_doctor_dashboard, name='corporate-doctor-dashboard/'),
    path('save-editor-content/', views.save_editor_content, name='save_editor_content'),
    path('get-editor-content/<str:study_id>/', views.get_editor_content, name='get_editor_content'),
    path('dental-checkup', views.dental_checkup_list, name='dental_checkup_list'),
    path('delete_all_patients_dental', views.delete_all_patients_dental, name='delete_all_patients_dental'),
    path('upload-dental-csv/', views.upload_dental_csv, name='upload_dental_csv'),
    path('doctor-checkup', views.doctor_checkup_list, name='doctor_checkup_list'),
    path('delete_all_patients_doctor', views.delete_all_patients_doctor, name='delete_all_patients_doctor'),
    path('upload-doctor-csv/', views.upload_doctor_csv, name='upload_doctor_csv'),
    # path('job_relaunch', views.job_relaunch, name='job_relaunch'),
    # path('fetch-failed-jobs/', views.fetch_failed_jobs, name='fetch_failed_jobs'),
    # path('retry-failed-jobs/', views.retry_failed_jobs, name='retry_failed_jobs'),
    path('pacsuploader/', views.pacsuploader, name='index'),
    path('upload_dicom_files/', views.upload_dicom_files, name='upload_dicom_files'),
    path('all-data/', views.all_patient_data, name='all_patient_data'),
    path('all-tb-data/', views.all_tb_data, name='all_tb_data'),
    path('ecgreporting/', views.patient_report, name='patient_report'),
    
    path('get-client-header-footer/', get_client_header_footer, name='get-client-header-footer'),
    
    path('save-template/', save_template, name='save-template'),
    path('get-template/<int:template_id>/',views.get_template, name='get_template'),
    path('get-dicom-notes/', get_dicom_notes, name='get_dicom_notes'),
    path('email-pdf-with-logo/<str:patient_id>/', views.email_pdf_with_logo, name='email_pdf_with_logo'),
    path('email-pdf-raw/<str:patient_id>/', views.email_pdf_raw, name='email_pdf_raw'),

    # BY Gautam Suri
    path('send-report-email/', views.send_report_email, name='send_report_email'),

    path('test-email-ui/', views.test_email_template),

    path('email-pdf-with-logo/<str:patient_id>/', views.email_pdf_with_logo, name='email_pdf_with_logo'),

    path('create-faq/', views.create_faq, name='create_faq'),
    path('view-faq/', views.view_faq, name='view_faq'),


] 
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
