# Generated by Django 5.1.3 on 2024-12-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_edit_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_body_part_examined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_patient_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_patient_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_referring_doctor_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_study_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_study_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_whatsapp_number',
            field=models.BooleanField(default=False),
        ),
    ]
