# Generated by Django 5.1 on 2024-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecg_jpgs/'),
        ),
    ]
