# Generated by Django 5.1 on 2024-09-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patientdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='companylogo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='signature',
            field=models.FileField(blank=True, default=None, null=True, upload_to='signatures/'),
        ),
    ]
