# Generated by Django 5.1.3 on 2024-12-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_can_edit_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomdata',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
