# Generated by Django 5.1.3 on 2024-12-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_dicomdata_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayreport',
            name='dicom_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xray_reports', to='users.dicomdata'),
        ),
    ]
