# Generated by Django 5.1 on 2024-09-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_personalinfo_companylogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='companylogo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/companylogos/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='signature',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/signatures/'),
        ),
    ]
