# Generated by Django 5.1 on 2024-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_personalinfo_companylogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='PatientName',
            field=models.CharField(max_length=255),
        ),
    ]
