# Generated by Django 5.1.3 on 2024-12-19 09:31

import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_xrayreport_dicom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='Modality',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='recived_on_db',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='recived_on_orthanc',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='study_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='notes',
            field=models.TextField(default=True, max_length=50000),
        ),
        migrations.CreateModel(
            name='PatientHistoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_file', models.FileField(help_text='Upload patient history files (PDF, JPEG, PNG).', storage=storages.backends.s3.S3Storage(), upload_to='patient_history_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_files', to='users.dicomdata')),
            ],
        ),
    ]
