# Generated by Django 5.1 on 2024-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_patientdetails_patientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomdata',
            name='accession_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
