# Generated by Django 5.1 on 2024-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_dicomdata_accession_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayreport',
            name='accession_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xrayreport',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xrayreport',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
