# Generated by Django 5.1.3 on 2024-12-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dicomdata_modality_dicomdata_recived_on_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomdata',
            name='Modality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
