# Generated by Django 5.1 on 2024-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_xrayreport_accession_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiometryreport',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiopatientdetails',
            name='PatientId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='audiopatientdetails',
            name='PatientName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='optometryreport',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsreport',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
