# Generated by Django 5.1.3 on 2024-12-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_dicomdata_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomdata',
            name='recived_on_db',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='recived_on_orthanc',
            field=models.TimeField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='study_time',
            field=models.TimeField(blank=True, max_length=250, null=True),
        ),
    ]
