# Generated by Django 5.1 on 2024-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_audiometryreport_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomdata',
            name='age',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='body_part_examined',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='gender',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='patient_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='patient_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='study_date',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='study_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='location',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='acccnprphone',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='accountcnpr',
            field=models.CharField(max_length=215),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='altcnprdesignation',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='altcnprname',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='altcnprphone',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='cnprdesignation',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='cnprname',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='cnprphone',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='instpersonalinfo',
            name='emailfraccount',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='ColorBlindness',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='FarVisionLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='FarVisionRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='NearVisionLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='NearVisionRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='PatientId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='PatientName',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='ReportDate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='TestDate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='age',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='optopatientdetails',
            name='gender',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='HeartRate',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='PRInterval',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='ReportDate',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='TestDate',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='age',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='gender',
            field=models.CharField(max_length=215),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='AddLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='AddRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='AxisLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='AxisRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='ColorBlindness',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='CylindricalLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='CylindricalRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='FarVisionLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='FarVisionRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='NearVisionLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='NearVisionRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='PatientId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='PatientName',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='ReportDate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='SphericalLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='SphericalRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='TestDate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='age',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='altphone',
            field=models.CharField(blank=True, default=None, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='cnfpassword',
            field=models.CharField(blank=True, default=None, max_length=212, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='Date',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='Hepatitis_E_Batch_No',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='Hepatitis_E_Expiry_Date',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='Hepatitis_E_Manufacturing_Date',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='PatientId',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='PatientName',
            field=models.CharField(max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='Typhoid_Batch_No',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='Typhoid_Expiry_Date',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='Typhoid_Manufacturing_Date',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='age',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationpatientdetails',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='PatientId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='PatientName',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='ReportDate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='TestDate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='age',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='blood',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='gender',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='pulse',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vitalpatientdetails',
            name='weight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='xrayreport',
            name='accession_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xrayreport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xrayreport',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
