# Generated by Django 5.1.3 on 2024-12-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_dicomdata_recived_on_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomdata',
            name='recived_on_db',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
