# Generated by Django 5.1 on 2024-10-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_dicomfile_dicom_file_alter_jpegfile_jpeg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='dicom_file',
            field=models.FileField(upload_to='dicom_files/'),
        ),
        migrations.AlterField(
            model_name='jpegfile',
            name='jpeg_file',
            field=models.ImageField(upload_to='jpeg_files/'),
        ),
    ]
