# Generated by Django 5.1 on 2024-10-05 09:33

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_dicomfile_dicom_file_alter_jpegfile_jpeg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='dicom_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='dicom_files/'),
        ),
        migrations.AlterField(
            model_name='jpegfile',
            name='jpeg_file',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='jpeg_files/'),
        ),
    ]
