# Generated by Django 5.1.3 on 2024-12-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_corporatecoordinator_dicomdata_corporatecoordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatecoordinator',
            name='radiologist',
        ),
        migrations.AddField(
            model_name='corporatecoordinator',
            name='radiologist',
            field=models.ManyToManyField(blank=True, to='users.personalinfo'),
        ),
    ]
