# Generated by Django 5.0 on 2024-10-07 11:31

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_dicomfile_dicom_file_alter_jpegfile_jpeg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiometryreport',
            name='pdf_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/audiometry_pdfs/'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='pdf_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/ecg_pdfs/'),
        ),
        migrations.AlterField(
            model_name='optometryreport',
            name='pdf_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/optometry_pdfs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecg_jpgs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='reportimage',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecg_graphs/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='companylogo',
            field=models.FileField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(), upload_to='static/companylogos/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='signature',
            field=models.FileField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(), upload_to='static/signatures/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='uploadpicture',
            field=models.FileField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='qualificationdetails',
            name='mbbsdegree',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='qualificationdetails',
            name='mbbsmarksheet',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='qualificationdetails',
            name='mddegree',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='qualificationdetails',
            name='tencertificate',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='qualificationdetails',
            name='twelvecertificate',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='vitalsreport',
            name='pdf_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/vitals_pdfs/'),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='regcecr',
            field=models.FileField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='xrayreport',
            name='pdf_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/xray_pdfs/'),
        ),
    ]
