# Generated by Django 5.0 on 2024-10-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_audiometryreport_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='companylogo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/companylogos/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='signature',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/signatures/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='uploadpicture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
