# Generated by Django 5.1.3 on 2024-12-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_corporatecoordinator_radiologist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistoryfile',
            name='history_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='patient_history_files/'),
        ),
    ]
