# Generated by Django 5.1.3 on 2024-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_personalinfo_companylogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='study_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
