# Generated by Django 5.1.3 on 2024-12-30 07:00

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_patienthistoryfile_history_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistoryfile',
            name='history_file',
            field=models.FileField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='patient_history_files/'),
        ),
    ]
