# Generated by Django 5.1.3 on 2025-01-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_patienthistoryfile_history_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='Mlc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
