# Generated by Django 5.1.3 on 2024-11-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_dicomdata_study_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='AddLeft',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='AddRight',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='AxisLeft',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='AxisRight',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='CylindricalLeft',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='CylindricalRight',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='SphericalLeft',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='SphericalRight',
        ),
    ]
