# Generated by Django 5.1.3 on 2025-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_dicomdata_mlc_dicomdata_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
