# Generated by Django 5.1.3 on 2025-01-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_dicomdata_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='twostepcheck',
            field=models.BooleanField(default=False),
        ),
    ]
