# Generated by Django 5.1.3 on 2025-02-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_dentalpatientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.CharField(max_length=250)),
                ('PatientName', models.CharField(max_length=270)),
                ('age', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('date', models.CharField(blank=True, max_length=250, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
