# Generated by Django 5.1.3 on 2025-02-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_ecgpatientdetails_xraypatientdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalpatientdetails',
            name='abdomen',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vitalpatientdetails',
            name='chest_exhale',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vitalpatientdetails',
            name='chest_inhale',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
