# Generated by Django 5.1.3 on 2025-03-08 09:04

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_personalinfo_uploadpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tbclient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='dicom_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jpegfile',
            name='jpeg_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patienthistoryfile',
            name='history_file',
            field=models.FileField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='patient_history_files/'),
        ),
    ]
