# Generated by Django 5.1.3 on 2025-03-08 09:05

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_client_tbclient_alter_dicomfile_dicom_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='dicom_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='dicom_files/'),
        ),
        migrations.AlterField(
            model_name='jpegfile',
            name='jpeg_file',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='jpeg_files/'),
        ),
    ]
