# Generated by Django 5.1.3 on 2025-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_dicomfile_dicom_file_alter_jpegfile_jpeg_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='AddLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='AddRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='AxisLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='AxisRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='CylindricalLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='CylindricalRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='SphericalLeft',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='SphericalRight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='pdf_file',
            field=models.FileField(upload_to='uploads/ecg_pdfs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecg_jpgs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='reportimage',
            field=models.FileField(blank=True, null=True, upload_to='ecg_graphs/'),
        ),
    ]
