# Generated by Django 5.1.3 on 2025-03-22 12:29

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_patientinfo_addleft_patientinfo_addright_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='institution_name',
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='pdf_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/ecg_pdfs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecg_jpgs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='reportimage',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecg_graphs/'),
        ),
        migrations.AlterField(
            model_name='patienthistoryfile',
            name='history_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='patient_history_files/'),
        ),
        migrations.AddField(
            model_name='client',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='users.institution'),
        ),
    ]
