# Generated by Django 5.1.3 on 2025-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_client_institutions_client_institution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='upload_footer',
            field=models.ImageField(blank=True, null=True, upload_to='footers/'),
        ),
        migrations.AddField(
            model_name='client',
            name='upload_header',
            field=models.ImageField(blank=True, null=True, upload_to='headers/'),
        ),
    ]
