# Generated by Django 5.1.3 on 2025-04-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_ckeditortemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='institution_name',
        ),
        migrations.AddField(
            model_name='client',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='users.institution'),
        ),
    ]
