# Generated by Django 5.1.3 on 2025-04-11 08:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_institution_remove_client_institution_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomdata',
            name='twostepcheck',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patienthistoryfile',
            name='history_file',
            field=models.FileField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='patient_history_files/'),
        ),
    ]
