# Generated by Django 5.1.3 on 2025-04-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_dicomdata_twostepcheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='NonReportable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
