# Generated by Django 5.1.3 on 2025-04-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_patientdetails_nonreportable_patientdetails_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayreport',
            name='pdf_on_db',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
