# Generated by Django 5.1.3 on 2025-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_xrayreport_pdf_on_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='marked_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='radiologist_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
