# Generated by Django 5.1.3 on 2025-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_dicomdata_marked_done_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='notes_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
