# Generated by Django 5.1.3 on 2025-07-07 10:40

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_dicomdata_notes_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistoryfile',
            name='history_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='patient_history_files/'),
        ),
        migrations.AlterField(
            model_name='patienthistoryfile',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
