# Generated by Django 5.1.3 on 2025-07-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_patienthistoryfile_history_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='upload_footer',
            field=models.FileField(blank=True, null=True, upload_to='footers/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='upload_header',
            field=models.FileField(blank=True, null=True, upload_to='headers/'),
        ),
    ]
