# Generated by Django 5.1.3 on 2025-07-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_client_upload_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_edit_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
