# Generated by Django 5.1.3 on 2025-08-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologistInstitutionRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutions', models.ManyToManyField(related_name='restricted_radiologists', to='users.institution')),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_institutions', to='users.personalinfo')),
            ],
            options={
                'unique_together': {('radiologist',)},
            },
        ),
    ]
