# Generated by Django 5.1.3 on 2025-09-04 07:08

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_patientdetails_image_ecgclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='studyInstanceUID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecg_jpgs/'),
        ),
    ]
