# Generated by Django 5.1.3 on 2025-09-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_dicomdata_studyinstanceuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomdata',
            old_name='studyInstanceUID',
            new_name='study_instance_uid',
        ),
    ]
