# Generated by Django 5.1.3 on 2025-09-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_rename_studyinstanceuid_dicomdata_study_instance_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSNATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('content', models.TextField()),
            ],
        ),
    ]
